### ISSUE TITLE
Is it necessary to use min.cells to filter out genes when we already did miQC to filter out low-quality cells?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [greenelab/miQC#8]
Hi there, 

In Seurat pipeline, there is a parameter min.cells to filter out genes expressed in low number of cells. 

Is it necessary to use min.cells to filter out genes when we already did miQC to filter out low-quality cells?

Thank you!

**Comment by arielah** [comment]
Hi! I'd say it depends on what type of experiment you're doing downstream (e.g. clustering/marker gene identification vs differential expression). The biggest change that miQC would make on the decision to filter out genes or not is to make sure your gene count threshold isn't too high given the number of low-quality cells that miQC removed. I don't use Seurat myself, but if it's possible I would set the min.cells parameter to be a percentage of the number of cells post-miQC instead of a flat cutoff. In my experiments (using scater), I remove genes that aren't expressed in at least 2.5% of post-miQC cells. Hope that's helpful.

**Comment by denvercal1234GitHub** [comment]
Thank you @arielah. In the Seurat workflow, we can only set the mincell parameter to filter out the genes first before applying miQC, because mincell is part of the CreateSeuratObject() and miQC requires a Seurat object. 

Do you think it is reasonable then to set the mincells as a proportion (I will decide this proportion based on visualizing the data), then apply miQC() ?

Also, do you have any advice on how to evaluate our own data to decide which model (non-linear vs linear mixture models) would be best suited?

Thank you again so much for your help!

**Comment by arielah** [comment]
Hi @denvercal1234GitHub, apologies for the long delay in response. I think your suggestion to set the mincells as a percentage of pre-filtering cells is probably the best for the Seurat workflow.

As for which kind of model to use, on my data I almost always use the linear model; when you have the "triangle" shape I discuss in the vignette (where at low gene counts you have some cells with low mitochondrial % and some high mitochondrial %, but at high gene counts you have more consistently low mitochondrial %), they will usually return similar results so I favor the simpler model. One tip for deciding if the non-linear model would be better for your data is to run `plotModel()` and see if you see a deep U-shape in the color gradation between dark and light blue. A shallow U is normal, but if it's too deep you'll lose a lot of cells because `filterCells()` will remove all the cells to the left of the bottom of the U. That's one sign that it might be worth trying a non-linear model. Hope that helps in the future!

**Comment by denvercal1234GitHub** [comment]
Thanks @arielah -- That is very helpful. Though, to use plotModel(), I will need to convert seurat object to sce object. Would be lovely if there is a more streamlined workflow for Seurat (on my Xmas wishlist lol). Great tool though. Love it!
